// <auto-generated />
using System;
using Blood_Bank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blood_Bank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601131819_UpdateModels1")]
    partial class UpdateModels1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodBankBloodRequest", b =>
                {
                    b.Property<int>("BloodBankUserID")
                        .HasColumnType("int");

                    b.Property<int>("BloodRequestsRequestId")
                        .HasColumnType("int");

                    b.HasKey("BloodBankUserID", "BloodRequestsRequestId");

                    b.HasIndex("BloodRequestsRequestId");

                    b.ToTable("BloodBankBloodRequest");
                });

            modelBuilder.Entity("Blood_Bank.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CenterAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("patientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("UserID");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HospitalUserID")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UnitId");

                    b.HasIndex("HospitalUserID");

                    b.HasIndex("InventoryId");

                    b.ToTable("BloodUnits");
                });

            modelBuilder.Entity("Blood_Bank.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("Blood_Bank.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("BloodBankUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalUserID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("NotificationId");

                    b.HasIndex("BloodBankUserID");

                    b.HasIndex("DonorId");

                    b.HasIndex("HospitalUserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Blood_Bank.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId")
                        .IsUnique();

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("Blood_Bank.Models.SosRequest", b =>
                {
                    b.Property<int>("SOSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SOSId"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalUserID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("SOSId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("HospitalUserID");

                    b.ToTable("SosRequests");
                });

            modelBuilder.Entity("Blood_Bank.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Blood_Bank.Models.Admin", b =>
                {
                    b.HasBaseType("Blood_Bank.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodBank", b =>
                {
                    b.HasBaseType("Blood_Bank.Models.User");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasIndex("InventoryId")
                        .IsUnique()
                        .HasFilter("[InventoryId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("BloodBank");
                });

            modelBuilder.Entity("Blood_Bank.Models.Donor", b =>
                {
                    b.HasBaseType("Blood_Bank.Models.User");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("TotalDonations")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Donor");
                });

            modelBuilder.Entity("Blood_Bank.Models.Hospital", b =>
                {
                    b.HasBaseType("Blood_Bank.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentUnits")
                        .HasColumnType("int");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Hospital");
                });

            modelBuilder.Entity("BloodBankBloodRequest", b =>
                {
                    b.HasOne("Blood_Bank.Models.BloodBank", null)
                        .WithMany()
                        .HasForeignKey("BloodBankUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood_Bank.Models.BloodRequest", null)
                        .WithMany()
                        .HasForeignKey("BloodRequestsRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blood_Bank.Models.Appointment", b =>
                {
                    b.HasOne("Blood_Bank.Models.Donor", "Donor")
                        .WithMany("Appointments")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodRequest", b =>
                {
                    b.HasOne("Blood_Bank.Models.Hospital", "Hospital")
                        .WithMany("BloodRequests")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodUnit", b =>
                {
                    b.HasOne("Blood_Bank.Models.Hospital", null)
                        .WithMany("BloodUnits")
                        .HasForeignKey("HospitalUserID");

                    b.HasOne("Blood_Bank.Models.Inventory", "Inventory")
                        .WithMany("BloodUnits")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Blood_Bank.Models.Notification", b =>
                {
                    b.HasOne("Blood_Bank.Models.BloodBank", "BloodBank")
                        .WithMany("notfications")
                        .HasForeignKey("BloodBankUserID");

                    b.HasOne("Blood_Bank.Models.Donor", "Donor")
                        .WithMany("Notifications")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood_Bank.Models.Hospital", null)
                        .WithMany("Notifications")
                        .HasForeignKey("HospitalUserID");

                    b.Navigation("BloodBank");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Blood_Bank.Models.Reward", b =>
                {
                    b.HasOne("Blood_Bank.Models.Donor", "Donor")
                        .WithOne("Reward")
                        .HasForeignKey("Blood_Bank.Models.Reward", "DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Blood_Bank.Models.SosRequest", b =>
                {
                    b.HasOne("Blood_Bank.Models.Hospital", "Hospital")
                        .WithMany("SosRequests")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood_Bank.Models.Hospital", null)
                        .WithMany("SOSRequests")
                        .HasForeignKey("HospitalUserID");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodBank", b =>
                {
                    b.HasOne("Blood_Bank.Models.Inventory", "Inventory")
                        .WithOne("BloodBank")
                        .HasForeignKey("Blood_Bank.Models.BloodBank", "InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Blood_Bank.Models.Inventory", b =>
                {
                    b.Navigation("BloodBank");

                    b.Navigation("BloodUnits");
                });

            modelBuilder.Entity("Blood_Bank.Models.BloodBank", b =>
                {
                    b.Navigation("notfications");
                });

            modelBuilder.Entity("Blood_Bank.Models.Donor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Blood_Bank.Models.Hospital", b =>
                {
                    b.Navigation("BloodRequests");

                    b.Navigation("BloodUnits");

                    b.Navigation("Notifications");

                    b.Navigation("SOSRequests");

                    b.Navigation("SosRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
