# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkjMiPgeHRBTdqJckl_sMG22Bbyz8Uwu
"""

# فك الضغط مع مراعاة المسافة في اسم الملف
!unzip "/content/Blood Dataset.zip" -d "/content/blood_data"

!pip install ultralytics

import os
import pandas as pd
import shutil
import random
from ultralytics import YOLO

dataset_path = '/content/blood_dataset_yolo'
images_src = '/content/blood_data/images'
csv_path = '/content/data.csv'

if os.path.exists(dataset_path): shutil.rmtree(dataset_path)
for sub in ['images/train', 'images/val', 'labels/train', 'labels/val']:
    os.makedirs(os.path.join(dataset_path, sub), exist_ok=True)


IMG_W, IMG_H = 640, 480
class_map = {'RBC': 0, 'WBC': 1, 'Platelets': 2}

df = pd.read_csv(csv_path, header=None)
df.columns = ['filename', 'cell_type', 'xmin', 'ymin', 'xmax', 'ymax']

grouped = df.groupby('filename')

for filename, group in grouped:
    label_name = filename.replace('.jpg', '.txt')
    label_path = os.path.join(images_src, label_name)

    with open(label_path, 'w') as f:
        for _, row in group.iterrows():
            cls_id = class_map.get(row['cell_type'], 0)

            x_center = (row['xmin'] + row['xmax']) / 2 / IMG_W
            y_center = (row['ymin'] + row['ymax']) / 2 / IMG_H
            w = (row['xmax'] - row['xmin']) / IMG_W
            h = (row['ymax'] - row['ymin']) / IMG_H

            f.write(f"{cls_id} {x_center:.6f} {y_center:.6f} {w:.6f} {h:.6f}\n")

all_images = [f for f in os.listdir(images_src) if f.endswith('.jpg')]
random.shuffle(all_images)
split = int(len(all_images) * 0.8)

def move_files(files, subset):
    for f in files:
        shutil.copy(os.path.join(images_src, f), os.path.join(dataset_path, f'images/{subset}/{f}'))
        label_f = f.replace('.jpg', '.txt')
        if os.path.exists(os.path.join(images_src, label_f)):
            shutil.copy(os.path.join(images_src, label_f), os.path.join(dataset_path, f'labels/{subset}/{label_f}'))

move_files(all_images[:split], 'train')
move_files(all_images[split:], 'val')

print(f"✅ تم تحويل وتقسيم {len(all_images)} صورة بنجاح!")

yaml_content = f"""
path: {dataset_path}
train: images/train
val: images/val
names:
  0: RBC
  1: WBC
  2: Platelets
"""
with open("blood_final.yaml", "w") as f:
    f.write(yaml_content)

print("🚀 جاري بدء التدريب باستخدام GPU...")
model = YOLO('yolov8n.pt')
model.train(data='blood_final.yaml', epochs=50, imgsz=640, device=0)

from google.colab import files
files.download('/content/runs/detect/train2/weights/best.pt')

import glob

# 2. تجربة التقرير على أول صورة يجدها في مجلد التحقق (val)
val_images = glob.glob('/content/blood_dataset_yolo/images/val/*.jpg')

if len(val_images) > 0:
    sample_img = val_images[0] # يأخذ أول صورة موجودة فعلياً
    print(f"✅ جاري تحليل الصورة: {sample_img}")
    generate_medical_report(sample_img)
else:
    print("❌ لم يتم العثور على أي صور في مجلد /content/blood_dataset_yolo/images/val/")